import java.util.Stack;

public class FloodFillText {
    static String text = """
.....................................................
.....................................................
..########........#########.......########...........
..#......#........#.......#.......#......#...........
..#......#........#.......#.......#......#...........
..#......#........#.......#.......#......#...........
..########........#########.......########...........
.....................................................
..########....########....########....########.......
..#......#....#......#....#......#....#......#.......
..#......#....#......#....#......#....#......#.......
..########....########....########....########.......
.....................................................
..#######.........#######.........#######............
..#.....#.........#.....#.........#.....#............
..#.....#.........#.....#.........#.....#............
..#######.........#######.........#######............
.....................................................
.....................................................
.....................................................""";

    public static void main(String[] args) {
        StringBuilder sb = new StringBuilder(text);
        fill(sb, 3, 3, '.', 'o');
        fill(sb, 10, 9, '.', 'x');
        fill(sb, 16, 8, '.', '|');
        replaceBackground(sb, '.', '´');
        System.out.println(sb);
    }

    static void fill(StringBuilder sb, int x, int y, char target, char replacement) {
        int width = sb.indexOf("\n") + 1;
        Stack<Integer> stack = new Stack<>();
        stack.push(x * width + y);
        while (!stack.isEmpty()) {
            int pos = stack.pop();
            if (pos < 0 || pos >= sb.length() || sb.charAt(pos) != target) continue;
            sb.setCharAt(pos, replacement);
            stack.push(pos - 1);
            stack.push(pos + 1);
            stack.push(pos - width);
            stack.push(pos + width);
        }
    }

    static void replaceBackground(StringBuilder sb, char oldChar, char newChar) {
        for (int i = 0; i < sb.length(); i++) {
            if (sb.charAt(i) == oldChar) {
                sb.setCharAt(i, newChar);
            }
        }
    }
}